In [1]:
# path to your train/test/meta folders
DATA_PATH = 'data/'

# names of valuable files/folders
train_meta_fname = 'train.csv'
test_meta_fname = 'sample_submission.csv'
train_data_folder = 'train'
test_data_folder = 'test'

In [2]:
import numpy as np
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torchaudio
import torchvision
from torchaudio import transforms
from efficientnet_pytorch import EfficientNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from tqdm import tqdm

In [3]:
# set seeds
import random
import numpy as np

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.backends.cudnn.deterministic = True

In [4]:
df_train = pd.read_csv(os.path.join(DATA_PATH, train_meta_fname))
df_test = pd.read_csv(os.path.join(DATA_PATH, test_meta_fname))
df_train.head(2)

                      fname            label
0  8bcbcc394ba64fe85ed4.wav  Finger_snapping
1  00d77b917e241afa06f1.wav           Squeak

In [5]:
n_classes = df_train.label.nunique()
print(n_classes)
classes_dict = {cl:i for i,cl in enumerate(df_train.label.unique())}
df_train['label_encoded'] = df_train.label.map(classes_dict)
df_train.head()

41

                      fname            label  label_encoded
0  8bcbcc394ba64fe85ed4.wav  Finger_snapping              0
1  00d77b917e241afa06f1.wav           Squeak              1
2  17bb93b73b8e79234cb3.wav   Electric_piano              2
3  7d5c7a40a936136da55e.wav        Harmonica              3
4  17e0ee7565a33d6c2326.wav       Snare_drum              4

In [6]:
# https://github.com/lukemelas/EfficientNet-PyTorch
class BaseLineModel(nn.Module):
    
    def __init__(self, sample_rate=16000, n_classes=41):
        super().__init__()
        self.ms = torchaudio.transforms.MelSpectrogram(sample_rate=sample_rate, n_mels=128)  #new5
#         self.bn1 = nn.BatchNorm2d(1)
        
        self.freq_mask = transforms.FrequencyMasking(freq_mask_param=15)  #new5
        self.time_mask = transforms.TimeMasking(time_mask_param=35)       #new5
        
        self.cnn1 = nn.Conv2d(in_channels=1, out_channels=10, kernel_size=3, padding=1)
        self.cnn3 = nn.Conv2d(in_channels=10, out_channels=3, kernel_size=3, padding=1)
        
        self.features = EfficientNet.from_pretrained('efficientnet-b0')
        # use it as features
#         for param in self.features.parameters():
#             param.requires_grad = False
            
        self.lin1 = nn.Linear(1000, 333)

        self.dropout = nn.Dropout(0.3)  # new2
        
        self.lin2 = nn.Linear(333, 111)
                
        self.lin3 = nn.Linear(111, n_classes)
        
    def forward(self, x):
        x = self.ms(x)
#         x = self.bn1(x)

        x = torch.log(x + 1e-6) # new1

        if self.training:
            x = self.freq_mask(x)   #new5
            x = self.time_mask(x)   #new5
        
        x = F.relu(self.cnn1(x))
        x = F.relu(self.cnn3(x))
        
        x = self.features(x)

        x = x.view(x.shape[0], -1)
        x = F.relu(x)
        
        x = self.dropout(F.relu(self.lin1(x)))  # new2
        x = self.dropout(F.relu(self.lin2(x)))  # new2
        x = self.lin3(x)
        return x
    
    def inference(self, x):
        x = self.forward(x)
        x = F.softmax(x, dim=1)
        return x

In [7]:
def sample_or_pad(waveform, wav_len=32000):
    m, n = waveform.shape
    if n < wav_len:
        padded_wav = torch.zeros(1, wav_len)
        padded_wav[:, :n] = waveform
        return padded_wav
    elif n > wav_len:
        offset = np.random.randint(0, n - wav_len)
        sampled_wav = waveform[:, offset:offset+wav_len]
        return sampled_wav
    else:
        return waveform
        
class EventDetectionDataset(Dataset):
    def __init__(self, data_path, x, y=None):
        self.x = x
        self.y = y
        self.data_path = data_path
    
    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        path2wav = os.path.join(self.data_path, self.x[idx])
        waveform, sample_rate = torchaudio.load(path2wav)
        waveform = sample_or_pad(waveform)
        if self.y is not None:
            return waveform, self.y[idx]
        return waveform

In [8]:
X_train, X_val, y_train, y_val = train_test_split(
    df_train.fname.values,
    df_train.label_encoded.values, 
    test_size=0.2,
    random_state=42,
    stratify=df_train.label_encoded.values  # new3
)

train_loader = DataLoader(
                        EventDetectionDataset(os.path.join(DATA_PATH, train_data_folder), X_train, y_train),
                        batch_size=41,
                        shuffle=True  # new3
                )
val_loader = DataLoader(
                        EventDetectionDataset(os.path.join(DATA_PATH, train_data_folder), X_val, y_val),
                        batch_size=41
                )
test_loader = DataLoader(
                        EventDetectionDataset(os.path.join(DATA_PATH, test_data_folder), df_test.fname.values, None),
                        batch_size=41, shuffle=False
                )

In [9]:
def eval_model(model, eval_dataset):
    model.eval()
    forecast, true_labs = [], []
    with torch.no_grad():
        for wavs, labs in tqdm(eval_dataset):
            wavs, labs = wavs.cuda(), labs.detach().numpy()
            true_labs.append(labs)
            outputs = model.inference(wavs)
            
            outputs = outputs.detach().cpu().numpy().argmax(axis=1)
            forecast.append(outputs)
    forecast = [x for sublist in forecast for x in sublist]
    true_labs = [x for sublist in true_labs for x in sublist]
    return f1_score(forecast, true_labs, average='macro')

In [10]:
criterion = nn.CrossEntropyLoss()
model = BaseLineModel()
model = model.cuda()
lr = 1e-3

optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)  # new4

C:\Users\admin77\miniconda3\envs\itmo-baseline\lib\site-packages\torchaudio\functional\functional.py:584: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(

Loaded pretrained weights for efficientnet-b0

In [11]:
n_epoch = 60
best_f1 = 0
for epoch in range(n_epoch):
    model.train()
    for wavs, labs in tqdm(train_loader):
        optimizer.zero_grad()
        wavs, labs = wavs.cuda(), labs.cuda()
        outputs = model(wavs)
        loss = criterion(outputs, labs)
        loss.backward()
        optimizer.step()
#     if epoch % 10 == 0:
    f1 = eval_model(model, val_loader)
    f1_train = eval_model(model, train_loader)
    print(f'epoch: {epoch}, f1_test: {f1}, f1_train: {f1_train}')
    if f1 > best_f1:
        best_f1 = f1
        torch.save(model.state_dict(), '../improvement_5_masking.pt')
        
    lr = lr * 0.95
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:33<00:00,  3.32it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:05<00:00,  5.24it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:15<00:00,  7.16it/s]

epoch: 0, f1_test: 0.060008927132123566, f1_train: 0.06797003279689856

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:29<00:00,  3.77it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.30it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:15<00:00,  7.09it/s]

epoch: 1, f1_test: 0.08952002376436269, f1_train: 0.10120426026921003

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:29<00:00,  3.78it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:14<00:00,  7.41it/s]

epoch: 2, f1_test: 0.32004757572998355, f1_train: 0.35873988931026574

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.29it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.52it/s]

epoch: 3, f1_test: 0.4026776275002137, f1_train: 0.439171032427968

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.45it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.37it/s]

epoch: 4, f1_test: 0.4688243129345978, f1_train: 0.5348806686959835

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.96it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:15<00:00,  7.35it/s]

epoch: 5, f1_test: 0.46477025532505173, f1_train: 0.5467592053299943

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.27it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:14<00:00,  7.54it/s]

epoch: 6, f1_test: 0.4930589946192227, f1_train: 0.5687329668123287

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.63it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.59it/s]

epoch: 7, f1_test: 0.5526309756302132, f1_train: 0.6357538878506253

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.50it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.18it/s]

epoch: 8, f1_test: 0.5519232226139114, f1_train: 0.6418930472535423

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:27<00:00,  4.11it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.11it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:14<00:00,  7.84it/s]

epoch: 9, f1_test: 0.5655167334170176, f1_train: 0.679697066779713

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.27it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.27it/s]

epoch: 10, f1_test: 0.6026120054779711, f1_train: 0.7150826621094429

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.00it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.07it/s]

epoch: 11, f1_test: 0.6243508425784016, f1_train: 0.7402823516623462

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.86it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.84it/s]

epoch: 12, f1_test: 0.6327805856021179, f1_train: 0.7536850693079385

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.61it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.67it/s]

epoch: 13, f1_test: 0.648308550919395, f1_train: 0.7591939453231105

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.32it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.57it/s]

epoch: 14, f1_test: 0.6353936753592562, f1_train: 0.7764789817363057

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.52it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.63it/s]

epoch: 15, f1_test: 0.6711521647355587, f1_train: 0.8053587201678717

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.42it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.49it/s]

epoch: 16, f1_test: 0.6744628189400463, f1_train: 0.8224885623277222

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.74it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.72it/s]

epoch: 17, f1_test: 0.6730384811358545, f1_train: 0.8253882123016377

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.80it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.63it/s]

epoch: 18, f1_test: 0.6762942525246923, f1_train: 0.8336339854510866

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.78it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.72it/s]

epoch: 19, f1_test: 0.7102318554083811, f1_train: 0.8471930037283611

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.38it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.40it/s]

epoch: 20, f1_test: 0.6898482409599721, f1_train: 0.8446344746069674

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.73it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.64it/s]

epoch: 21, f1_test: 0.7083031298093968, f1_train: 0.8573381020582792

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.64it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.67it/s]

epoch: 22, f1_test: 0.7106882098564276, f1_train: 0.8658548570543506

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.63it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.64it/s]

epoch: 23, f1_test: 0.7179406197438393, f1_train: 0.871343194580695

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.75it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.73it/s]

epoch: 24, f1_test: 0.7126165732665117, f1_train: 0.871527237852116

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.78it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.58it/s]

epoch: 25, f1_test: 0.7067043090624705, f1_train: 0.8762766683079896

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.76it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.67it/s]

epoch: 26, f1_test: 0.7414694568966668, f1_train: 0.8923362137083973

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.72it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.65it/s]

epoch: 27, f1_test: 0.7102486106426953, f1_train: 0.892244243664483

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.89it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.80it/s]

epoch: 28, f1_test: 0.7415008450063353, f1_train: 0.9032436496064612

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.85it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.82it/s]

epoch: 29, f1_test: 0.7311237274890328, f1_train: 0.8939256564458221

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.79it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.78it/s]

epoch: 30, f1_test: 0.7283599162270635, f1_train: 0.9096914928388544

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.71it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.62it/s]

epoch: 31, f1_test: 0.7303382433159974, f1_train: 0.9082193781606891

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.74it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.63it/s]

epoch: 32, f1_test: 0.7260530877612832, f1_train: 0.9035012640730513

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.66it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.71it/s]

epoch: 33, f1_test: 0.7453684928557627, f1_train: 0.915864240729615

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.43it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.85it/s]

epoch: 34, f1_test: 0.7381170727287587, f1_train: 0.9205992265052888

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.79it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.78it/s]

epoch: 35, f1_test: 0.7409084935026324, f1_train: 0.9140942014446158

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.88it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.80it/s]

epoch: 36, f1_test: 0.7488314902753602, f1_train: 0.9196419941667028

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.71it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.72it/s]

epoch: 37, f1_test: 0.7365666465541572, f1_train: 0.921039878785307

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.76it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.70it/s]

epoch: 38, f1_test: 0.7336157982256525, f1_train: 0.9242382141283854

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.71it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.88it/s]

epoch: 39, f1_test: 0.7552094769134763, f1_train: 0.9322583552921928

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.72it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.78it/s]

epoch: 40, f1_test: 0.7406627806475654, f1_train: 0.9315816498003049

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.67it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.66it/s]

epoch: 41, f1_test: 0.7484618466716733, f1_train: 0.938542118876943

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.57it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.56it/s]

epoch: 42, f1_test: 0.7392629846099587, f1_train: 0.9334452198092446

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.61it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.72it/s]

epoch: 43, f1_test: 0.752445024077945, f1_train: 0.9412519648907137

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.73it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.69it/s]

epoch: 44, f1_test: 0.7516733657560051, f1_train: 0.9353987188419052

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.53it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.67it/s]

epoch: 45, f1_test: 0.7613894451553319, f1_train: 0.9418740973650497

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.76it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.77it/s]

epoch: 46, f1_test: 0.7448639276293009, f1_train: 0.9384986379113275

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.77it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.85it/s]

epoch: 47, f1_test: 0.7587943630090846, f1_train: 0.9397421181357211

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.65it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.42it/s]

epoch: 48, f1_test: 0.7631095826884388, f1_train: 0.9414348537580584

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.69it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.72it/s]

epoch: 49, f1_test: 0.7590572932820555, f1_train: 0.9464453310408545

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.64it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.66it/s]

epoch: 50, f1_test: 0.7661848579962209, f1_train: 0.9435905825114715

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.81it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.86it/s]

epoch: 51, f1_test: 0.7690230216395935, f1_train: 0.9455555640386026

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.74it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.58it/s]

epoch: 52, f1_test: 0.7485453297638508, f1_train: 0.9468668216541548

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.91it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.63it/s]

epoch: 53, f1_test: 0.7682144901858863, f1_train: 0.9446118279997519

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.34it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.14it/s]

epoch: 54, f1_test: 0.7545490243896915, f1_train: 0.9453733517406756

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.13it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.94it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:14<00:00,  7.79it/s]

epoch: 55, f1_test: 0.745162703870072, f1_train: 0.9504413341474511

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:50<00:00,  2.21it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:12<00:00,  2.24it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:29<00:00,  3.70it/s]

epoch: 56, f1_test: 0.7515596440692613, f1_train: 0.9485702136941225

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.85it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.65it/s]

epoch: 57, f1_test: 0.7512693996747739, f1_train: 0.9515554148235711

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.38it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:13<00:00,  8.15it/s]

epoch: 58, f1_test: 0.7598380084374994, f1_train: 0.9501592228794604

100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:26<00:00,  4.14it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  8.69it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 111/111 [00:12<00:00,  8.60it/s]

epoch: 59, f1_test: 0.7441118942551446, f1_train: 0.9507225674752023

In [12]:
# make a model
model_name = 'improvement_5_masking.pt'
model = BaseLineModel().cuda()
model.load_state_dict(torch.load(os.path.join('..', model_name)))
model.eval()
forecast = []
with torch.no_grad():
    for wavs in tqdm(test_loader):
        wavs = wavs.cuda()
        outputs = model.inference(wavs)
        outputs = outputs.detach().cpu().numpy().argmax(axis=1)
        forecast.append(outputs)
forecast = [x for sublist in forecast for x in sublist]
decoder = {classes_dict[cl]:cl for cl in classes_dict}
forecast = pd.Series(forecast).map(decoder)
df_test['label'] = forecast
df_test.to_csv(f'{model_name}.csv', index=None)

C:\Users\admin77\miniconda3\envs\itmo-baseline\lib\site-packages\torchaudio\functional\functional.py:584: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(

Loaded pretrained weights for efficientnet-b0

C:\Users\admin77\AppData\Local\Temp\ipykernel_2364\2646536096.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(os.path.join('..', model_name)))
100%|██████████████████████████████████████████████████████████████████████████████████| 93/93 [00:38<00:00,  2.40it/s]